name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: npm install

      - run: npm run build

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/SWAMP CAMP-darwin-x64/SWAMP CAMP.app,build/SWAMP CAMP-win32-x64/SWAMP CAMP.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ matrix.os }}
