name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        
    - run: npm install
    
    - run: npm run build
        
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
